let token=localStorage.getItem("fitbuddy_token");
const $=id=>document.getElementById(id);
function showAuth(which){$("registerForm").classList.toggle("hidden",which!=="register");$("loginForm").classList.toggle("hidden",which!=="login");document.querySelectorAll(".tab").forEach((b,i)=>b.classList.toggle("active",(which==="register"?i===0:i===1)));$("authMsg").textContent=""}
async function api(url,options={}){options.headers={"Content-Type":"application/json",...(options.headers||{})};if(token)options.headers.Authorization="Bearer "+token;const r=await fetch(url,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||"Something went wrong.");return d}
async function register(e){e.preventDefault();try{const d=await api("/api/register",{method:"POST",body:JSON.stringify({name:$("regName").value,email:$("regEmail").value,password:$("regPassword").value})});token=d.token;localStorage.setItem("fitbuddy_token",token);openApp(d.user)}catch(x){$("authMsg").textContent=x.message}}
async function login(e){e.preventDefault();try{const d=await api("/api/login",{method:"POST",body:JSON.stringify({email:$("loginEmail").value,password:$("loginPassword").value})});token=d.token;localStorage.setItem("fitbuddy_token",token);openApp(d.user);loadMe()}catch(x){$("authMsg").textContent=x.message}}
function logout(){localStorage.removeItem("fitbuddy_token");token=null;$("appView").classList.add("hidden");$("authView").classList.remove("hidden")}
function openApp(u){$("authView").classList.add("hidden");$("appView").classList.remove("hidden");$("welcome").textContent="Hi, "+u.name+" BUDDY  🤍👋"}
async function loadMe(){if(!token)return;try{const d=await api("/api/me");openApp(d.user);if(d.profile)fillProfile(d.profile)}catch{logout()}}
function fillProfile(p){$("age").value=p.age||"";$("gender").value=p.gender||"Prefer not to say";$("height").value=p.height_cm||"";$("weight").value=p.weight_kg||"";$("goal").value=p.goal||"general wellness";$("activity").value=p.activity_level||"moderate";$("experience").value=p.experience||"beginner";$("equipment").value=p.equipment||"bodyweight";$("diet").value=p.dietary_preference||"balanced";$("minutes").value=p.workout_minutes||30}
async function saveProfile(e){e.preventDefault();const b={age:+$("age").value,gender:$("gender").value,height_cm:+$("height").value,weight_kg:+$("weight").value,goal:$("goal").value,activity_level:$("activity").value,experience:$("experience").value,equipment:$("equipment").value,dietary_preference:$("diet").value,workout_minutes:+$("minutes").value};try{const d=await api("/api/profile",{method:"POST",body:JSON.stringify(b)});$("profileMsg").style.color="#4a9134";$("profileMsg").textContent=d.message}catch(x){$("profileMsg").textContent=x.message}}
function generate(){generatePlan("/api/plan")}function regenerate(){generatePlan("/api/plan/regenerate")}
async function generatePlan(url){$("planMsg").textContent="Generating your plan...";try{const d=await api(url,{method:"POST",body:JSON.stringify({feedback:$("feedback").value})});renderPlan(d.plan,d.mode);$("planMsg").style.color="#4a9134";$("planMsg").textContent=d.mode==="gemini"?"Generated with Gemini AI.":"Generated in demo/fallback mode. Add GEMINI_API_KEY for Gemini AI."}catch(x){$("planMsg").textContent=x.message}}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function renderPlan(p,mode){$("plan").classList.remove("hidden");$("plan").innerHTML=`<div class="plan-head"><div><div class="badge">${esc(mode==="gemini"?"GEMINI AI":"DEMO MODE")}</div><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p></div></div><div class="days">${(p.days||[]).map(d=>`<article class="day"><div class="mini">${esc(d.day)} · ${esc(d.duration_minutes)} min · ${esc(d.intensity)}</div><h4>${esc(d.focus)}</h4><strong>Workout</strong><ul>${(d.workout||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul><strong>Food ideas</strong><ul>${(d.food||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul><p><strong>Recovery:</strong> ${esc(d.recovery)}</p></article>`).join("")}</div><div class="two" style="margin-top:20px"><div><h4>Nutrition</h4><ul>${(p.nutrition||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div><h4>Safety</h4><p>${esc(p.safety)}</p></div></div>`;$("plan").scrollIntoView({behavior:"smooth"})}
loadMe();
